//已完成
#include<stdio.h>
#include<stdlib.h>
#include<string.h>
double sz1[100];// 数字数组
int sz2[100];//标志数组
double sz3[100];//数字数组
int sz4[100];//标志数组
char sz[10000];//初始输入数组
int main()//定义标志数组a^n=n，x=-1，+=-2，-=-3，*=-4，/=-5，（=-6，）=-7
{
	printf("ZZS ️All Rights Reserved\n多项式化简程序\n请输入需要化简的多项式:\n");
	int i,j;
	j=0;//第一部分:数字的输入与分类处理14-136行
	scanf("%s",sz);//输入初始字符串
	printf("f(x)=");
	for(i=0;sz[i];++i)//输入的字符串转化为浮点数组
	{
		if(sz[i]=='x'||sz[i]=='X') //判断X并调整大小字母
		{
			if(sz[i-1]=='-')//判断x的系数为-1
			{
				sz1[j]=1;
				j++;
			}
			sz2[j]=-1;
			j++;
			if(sz[i+1]=='+'||sz[i+1]=='-'||sz[i+1]=='*'||sz[i+1]=='/'||sz[i+1]=='\0')//处理指数1
			{
				sz2[j]=1;
				j++;
			}
		}
		else if(sz[i]=='+')//判断+
		{
			sz2[j]=-2;
			j++;
		}
		else if(sz[i]=='.')//判断小数点
		{
			sz2[j]=-8;
			j++;
		}
		else if(sz[i]=='-')//判断-
		{
			sz2[j]=-3;
			j++;
		}
		else if(sz[i]=='*')//判断*
		{
			sz2[j]=-4;
			j++;
		}
		else if(sz[i]=='/')//判断/
		{
			sz2[j]=-5;
			j++;
		}
		else if(sz[i]=='^')//判断幂
		{
			i++;
			while(sz[i]>='0'&&sz[i]<='9')
			{
				sz2[j]=sz2[j]*10;
				sz2[j]=sz2[j]+sz[i]-'0';
				i++;
			}
			j++;
			i--;
		}
		else if(sz[i]=='(')//判断括号
		{
			sz2[j]=-6;
			j++;
		}
		else if(sz[i]==')')//判断括号
		{
			sz2[j]=-7;
			j++;
		}
		else//判断数字
			{
			while(sz[i]>='0'&&sz[i]<='9')
				{
				sz1[j]=sz1[j]*10;
				sz1[j]=sz1[j]+sz[i]-'0';
				i++;
				}
			j++;
			i--;
			}
	}
	for(i=0;i<=90;++i)//输入完成后整理小数
	{
		if(sz2[i]==-8)
		{
			while(sz1[i+1]>=1)
			{
				sz1[i+1]=sz1[i+1]/10;
			}
			sz1[i-1]=sz1[i-1]+sz1[i+1];
			sz1[i+1]=0;
			sz2[i]=0;
		}
	}
	for(i=0;i<=90;++i)//处理数组多余的0
		{
			sz3[i]=sz1[i];
			sz1[i]=0;
			sz4[i]=sz2[i];
			sz2[i]=0;
		}
		j=0;
		for(i=0;i<=90;++i)
		{
			if(sz3[i]==0&&sz4[i]==0)
			{
			}
			else
			{
				sz1[j]=sz3[i];
				sz2[j]=sz4[i];
				j++;
			}
		}
		memset(sz3,0,sizeof(sz3));
		memset(sz4,0,sizeof(sz4));//去0整理器
	for(i=0;i<=90;i++)//减号变加号
	{
		if(sz2[i]==-3&&sz1[i+1]>0)
		{
			sz1[i+1]=-sz1[i+1];
			sz2[i]=-2;
		}
	}//第一部分:数字的输入与分类处理14-136行
	int panduan=0;//第二部分:括号内的计算137-
	double plus;
	int k;
	for(i=90;i>=0;--i)//2.1乘方器
	{
		if(sz2[i]==-7)//括号判断器
			panduan=1;
		else if(sz2[i]==-6)
			panduan=0;
		if(panduan==1&&sz2[i]>0)//乘方器主体
		{
			plus=sz1[i-1];
			for(k=1;k<sz2[i];++k)
			{
				sz1[i-1]=sz1[i-1]*plus;
			}
			sz2[i]=0;
		}
	}
	for(i=0;i<=90;++i)//去0整理器
	{
		sz3[i]=sz1[i];
		sz1[i]=0;
		sz4[i]=sz2[i];
		sz2[i]=0;
	}
	j=0;
	for(i=0;i<=90;++i)
	{
		if(sz3[i]==0&&sz4[i]==0)
		{
		}
		else
		{
			sz1[j]=sz3[i];
			sz2[j]=sz4[i];
			j++;
		}
	}
	memset(sz3,0,sizeof(sz3));
	memset(sz4,0,sizeof(sz4));
	for(i=90;i>=0;--i)//2.2乘除法器
	{
		if(sz2[i]==-7)//括号判断器
			panduan=1;
		else if(sz2[i]==-6)
			panduan=0;
		if(panduan==1&&sz2[i]==-4)//2.2.1乘法器主体
		{
			sz1[i-1]=sz1[i-1]*sz1[i+1];
			sz1[i+1]=0;
			sz2[i]=0;
		}
		else if(panduan==1&&sz2[i]==-5)//2.2.2除法器主体
		{
			sz1[i+1]=1/sz1[i+1];
			sz1[i-1]=sz1[i-1]*sz1[i+1];
			sz1[i+1]=0;
			sz2[i]=0;
		}
	}
	for(i=0;i<=90;++i)//去0整理器
		{
			sz3[i]=sz1[i];
			sz1[i]=0.0;
			sz4[i]=sz2[i];
			sz2[i]=0;
		}
		j=0;
		for(i=0;i<=90;++i)
		{
			if(sz3[i]==0&&sz4[i]==0)
			{
			}
			else
			{
				sz1[j]=sz3[i];
				sz2[j]=sz4[i];
				j++;
			}
		}
		memset(sz3,0,sizeof(sz3));
		memset(sz4,0,sizeof(sz4));
	for(i=90;i>=0;--i)//2.3加减法器
	{
		if(sz2[i]==-7)//括号判断器
			panduan=1;
		else if(sz2[i]==-6)
			panduan=0;
		if(panduan==1&&sz2[i]==-2)//2.3.1加法器主体
		{
			sz1[i-1]=sz1[i-1]+sz1[i+1];
			sz1[i+1]=0;
			sz2[i]=0;
		}
		else if(panduan==1&&sz2[i]==-3)//2.3.2减法器主体
		{
			sz1[i+1]=0-sz1[i+1];
			sz1[i-1]=sz1[i-1]+sz1[i+1];
			sz1[i+1]=0;
			sz2[i]=0;
		}
	}
	for(i=0;i<=90;++i)//去0整理器
		{
			sz3[i]=sz1[i];
			sz1[i]=0;
			sz4[i]=sz2[i];
			sz2[i]=0;
		}
		j=0;
		for(i=0;i<=90;++i)
		{
			if(sz3[i]==0&&sz4[i]==0)
			{
			}
			else
			{
				sz1[j]=sz3[i];
				sz2[j]=sz4[i];
				j++;
			}
		}
		memset(sz3,0,sizeof(sz3));
		memset(sz4,0,sizeof(sz4));
	for(i=0;i<=90;++i)//2.4去括号器
		if(sz2[i]==-6||sz2[i]==-7)
			sz2[i]=0;//去括号器主体
	for(i=0;i<=90;++i)//去0整理器
		{
			sz3[i]=sz1[i];
			sz1[i]=0;
			sz4[i]=sz2[i];
			sz2[i]=0;
		}
		j=0;
		for(i=0;i<=90;++i)
		{
			if(sz3[i]==0&&sz4[i]==0)
			{
			}
			else
			{
				sz1[j]=sz3[i];
				sz2[j]=sz4[i];
				j++;
			}
		}
		memset(sz3,0,sizeof(sz3));
		memset(sz4,0,sizeof(sz4));
	for(i=90;i>=0;--i)//第三部分括号外处理:3.1括号外乘方器
		{
			if(sz2[i]>0&&sz2[i-1]!=-1)
			{
				plus=sz1[i-1];
				for(k=1;k<sz2[i];++k)
				{
					sz1[i-1]=sz1[i-1]*plus;
				}
				sz2[i]=0;
			}//乘方器主体
		}
		for(i=0;i<=90;++i)//去0整理器
		{
			sz3[i]=sz1[i];
			sz1[i]=0;
			sz4[i]=sz2[i];
			sz2[i]=0;
		}
		j=0;
		for(i=0;i<=90;++i)
		{
			if(sz3[i]==0&&sz4[i]==0)
			{
			}
			else
			{
				sz1[j]=sz3[i];
				sz2[j]=sz4[i];
				j++;
			}
		}
	memset(sz3,0,sizeof(sz3));
	memset(sz4,0,sizeof(sz4));
	for(i=90;i>=0;--i)//3.2括号外的乘除法器
	{
		if(sz2[i]==-4)
		{
			sz1[i-1]=sz1[i-1]*sz1[i+1];
			sz1[i+1]=0;
			sz2[i]=0;
		}
		else if(sz2[i]==-5)
			{
			sz1[i+1]=1/sz1[i+1];
			sz1[i-1]=sz1[i-1]*sz1[i+1];
			sz1[i+1]=0;
			sz2[i]=0;
			}
	}
	for(i=0;i<=90;++i)//去0整理器
	{
		sz3[i]=sz1[i];
		sz1[i]=0;
		sz4[i]=sz2[i];
		sz2[i]=0;
	}
	j=0;
	for(i=0;i<=90;++i)
	{
		if(sz3[i]==0&&sz4[i]==0)
		{

		}
		else
		{
			sz1[j]=sz3[i];
			sz2[j]=sz4[i];
			j++;
		}
	}
	memset(sz3,0,sizeof(sz3));
	memset(sz4,0,sizeof(sz4));
	int max=0;//第4部分：同类项合并
	i=0;
	j=0;
	k=0;
	plus=0;
	for(i=0;i<=90;i++)
	{
		if(sz2[i]==-3)
			{
			sz1[i+1]=-sz1[i+1];
			sz2[i]=0;
			}
		if(sz2[i]>max)
			max=sz2[i];
	}
	for(i=max;i>=0;--i)
	{
		panduan=0;
		for(j=90;j>=0;--j)
		{
			if(sz2[j]==-1&&sz2[j+1]==i&&sz1[j-1]!=0)
			{
				plus+=sz1[j-1];
				panduan=1;
				sz1[j-1]=0;
				sz2[j]=0;
				sz2[j+1]=0;
			}
			else if(sz2[j]==-1&&sz2[j+1]==i&&sz1[j-1]==0)
			{
				plus++;
				panduan=1;
				sz2[j]=0;
				sz2[j+1]=0;
			}
		}
		if(panduan==1)
		{
			sz3[k++]=plus;
			sz4[k++]=-1;
			sz4[k++]=i;
			panduan=0;
			plus=0;
		}
	}
	for(j=90;j>=0;--j)
	{
		if((sz1[j]!=0)&&(sz2[j+1]!=-1))
		{
			plus+=sz1[j];
		}
	}
	sz3[k]=plus;//合并器主体
	for(i=0;i<=90;++i)//去0整理器
			{
				sz1[i]=sz3[i];
				sz3[i]=0;
				sz2[i]=sz4[i];
				sz4[i]=0;
			}
			j=0;
			for(i=0;i<=90;++i)
			{
				if(sz1[i]==0&&sz2[i]==0)
				{
				}
				else
				{
					sz3[j]=sz1[i];
					sz4[j]=sz2[i];
					j++;
				}
			}
			memset(sz1,0,sizeof(sz1));
			memset(sz2,0,sizeof(sz2));
	for(i=0;i<=90;++i)
	{
		sz1[i]=sz3[i];
		sz2[i]=sz4[i];
	}
	j=0;//第五部分：输出结果
	int a;//防止4.000情况
	if(sz1[0]==0&&sz2[0]==0)
	{
		printf("0");
		return 0;
	}
	while(1)
		{
			if(sz1[j]==0&&sz2[j]==0)
				break;
			else if(sz1[j]!=0)
			{
				if(sz1[j]==1&&sz2[j+1]==-1)
				{
					j++;
				}
				else if(sz1[j]==-1&&sz2[j+1]==-1)
				{
					printf("-");
					j++;
				}
				else
				{
					if(sz1[j]-(int)sz1[j]!=0)//4.1000情况
					printf("%lf",sz1[j]);
					else if(sz1[j]-(int)sz1[j]==0)//4.000情况
					{
						a=sz1[j];
						printf("%d",a);
					}
					j++;
				}

				if(sz1[j+1]>0)
					printf("+");
			}
			else if(sz1[j]==0&&sz2[j]==-1)
			{
				printf("x");
				j++;
			}
			else if(sz1[j]==0&&sz2[j]==-2)
			{
				printf("+");
				j++;
			}
			else if(sz1[j]==0&&sz2[j]==-3)
			{
				printf("-");
				j++;
			}
			else if(sz1[j]==0&&sz2[j]==-4)
			{
				printf("*");
				j++;
			}
			else if(sz1[j]==0&&sz2[j]==-5)
			{
				printf("/");
				j++;
			}
			else if(sz1[j]==0&&sz2[j]==-6)
			{
				printf("(");
				j++;
			}
			else if(sz1[j]==0&&sz2[j]==-7)
			{
				printf(")");
				j++;
			}
			else
			{
				if(sz2[j]!=1)//x^1情况
					printf("^%d",sz2[j]);
				j++;
				if(sz1[j]>0)
					printf("+");
			}
		}//字符的输出
	return 0;
}
